// Iranian Attack Pattern Evolution: True Promise 3 vs True Promise 4
// Comparative OSINT Analysis

#set text(font: "IBM Plex Sans", size: 10pt)
#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2cm, right: 2cm),
  header: context {
    if counter(page).get().first() > 1 [
      #set text(size: 8pt, fill: rgb("#666"))
      Iranian Attack Pattern Evolution: TP3 vs TP4 — Comparative OSINT Analysis
      #h(1fr)
      #counter(page).display()
    ]
  },
  footer: [
    #set text(size: 7pt, fill: rgb("#999"))
    #align(center)[
      AI-GENERATED (Anthropic Claude Sonnet 4.6) · Generated 05/03/26 · All facts require independent verification
    ]
  ]
)
#set par(justify: true, leading: 0.7em)
#set heading(numbering: "1.1")

// ============================================================
// TITLE PAGE
// ============================================================

#v(3cm)

#align(center)[
  #text(size: 28pt, weight: "bold", fill: rgb("#1a1a1a"))[
    Iranian Attack Pattern Evolution
  ]
  #v(0.5cm)
  #text(size: 16pt, fill: rgb("#444"))[
    Operation True Promise 3 (June 2025) vs \
    Operation True Promise 4 (February–March 2026)
  ]
  #v(1cm)
  #line(length: 60%, stroke: 1pt + rgb("#DC2626"))
  #v(0.8cm)
  #text(size: 12pt, fill: rgb("#666"))[
    Comparative OSINT Analysis
  ]
  #v(2cm)
  #text(size: 10pt, fill: rgb("#888"))[
    *Author:* Anthropic Claude Sonnet 4.6 (AI-generated analysis) \
    *Date of generation:* 05/03/26 \
    *Data status:* TP4 ongoing as of publication (19 waves recorded through 05/03/26) \
    *Classification:* Open source — no classified material \
    \
    #rect(fill: rgb("#FEF2F2"), inset: 0.6em, radius: 3pt, stroke: 0.5pt + rgb("#DC2626"))[
      #text(size: 8pt, fill: rgb("#991B1B"), weight: "bold")[
        This report was entirely generated by AI. All facts, figures, and analysis \
        must be independently verified before citation or use in decision-making.
      ]
    ]
  ]
]

#pagebreak()

// ============================================================
// TABLE OF CONTENTS
// ============================================================

#outline(indent: 1.5em, depth: 2)

#pagebreak()

// ============================================================
// 1. EXECUTIVE SUMMARY
// ============================================================

= Executive Summary

Iran's missile and drone campaigns against Israel have undergone a fundamental transformation between Operation True Promise 3 (TP3, June 2025) and Operation True Promise 4 (TP4, February–March 2026). This report identifies and documents six major shifts in Iranian attack doctrine, supported by wave-level data from 41 combined attack waves (22 in TP3, 19 in TP4 as of 05 March 2026).

#v(0.3cm)

#table(
  columns: (1fr, 1fr, 1fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#2563EB").lighten(85%) } else { none },
  align: center,
  [*Metric*], [*TP3 (Jun 2025)*], [*TP4 (Feb–Mar 2026)*],
  [Total waves], [22], [19 (ongoing)],
  [Duration], [12 days (Jun 13–24)], [6+ days (Feb 28–Mar 5+)],
  [Countries hit], [1 (Israel)], [12],
  [Avg inter-wave gap], [10.5 hours], [5.4 hours],
  [Drone waves], [7 of 22 (32%)], [16 of 19 (84%)],
  [BM waves], [22 of 22 (100%)], [18 of 19 (95%)],
  [Cruise missile waves], [0 of 22 (0%)], [3 of 19 (16%)],
  [US bases targeted], [0 waves], [16 waves (84%)],
  [Israel targeted], [22 of 22 (100%)], [14 of 19 (74%)],
  [Night launches (phase 0–1)], [8 of 22 (36%)], [8 of 19 (42%)],
  [Recorded fatalities], [33 killed], [1+ (ongoing)],
  [Estimated munitions (TP3)], [1,600–1,800+], [Data incomplete],
)

#v(0.3cm)

*Key finding:* TP4 represents a doctrinal shift from a focused, Israel-only ballistic missile campaign to a multi-theater, multi-domain operation integrating drones, ballistic missiles, and cruise missiles against both Israeli and US/coalition targets across 12 countries. Notably, US/coalition bases are targeted more frequently in TP4 (84% of waves) than Israel itself (74%), inverting TP3's exclusively Israel-focused targeting.

#pagebreak()

// ============================================================
// 2. ATTACK TEMPO
// ============================================================

= Attack Tempo and Operational Rhythm

== Inter-Wave Timing

The most immediate operational difference between TP3 and TP4 is attack tempo. TP4 waves arrive at nearly double the rate of TP3.

#figure(
  image("report_02_tempo.png", width: 100%),
  caption: [Inter-wave intervals in hours. TP4 (red) averages 5.4h between waves vs TP3 (blue) at 10.5h.],
)

*Evidence:*
- *TP3:* Average 10.5 hours between waves. Intervals ranged from 1.0h to 23.0h, suggesting a deliberate pacing strategy — likely driven by liquid-fuel missile reload times (Emad and Ghadr dominate TP3 with 20 and 21 waves respectively, both liquid-fueled MRBMs).
- *TP4:* Average 5.4 hours between waves. Maximum gap just 14.0h. This acceleration is consistent with greater reliance on solid-fuel missiles and pre-positioned drone launchers, which eliminate the 30+ minute liquid-fuel setup penalty.

The near-halving of inter-wave gaps suggests Iran learned from TP3 that spacing allowed Israeli/US defenses time to rearm and reposition interceptors. TP4's compressed tempo is designed to exhaust interceptor stocks more rapidly.

== Night vs Day Preference

#figure(
  image("report_08_night_day.png", width: 85%),
  caption: [Launch timing distribution by solar phase. TP3 launched 8 of 22 waves (36%) at night (phase 0); TP4 launched 8 of 19 waves (42%) at night. Both operations launch around the clock.],
)

TP4 shows a modest increase in night operations (42% vs 36%), consistent with exploiting reduced visual detection and complicating defensive targeting. However, the shift is not dramatic — Iran launches around the clock in both operations. TP4 also shows more daytime (phase 5) launches than TP3, driven by the multi-theater nature of the operation (Gulf targets require coordinated timing regardless of illumination conditions).

#pagebreak()

// ============================================================
// 3. FLIGHT TIMES AND WARNING WINDOWS
// ============================================================

= Ballistic Missile Flight Times and Defender Warning Windows

This is among the most operationally significant dimensions of the data. The time between Iranian missile launch and Israeli impact determines the defender's engagement window — the seconds available for detection, tracking, classification, and interception.

#figure(
  image("report_07_flight_times.png", width: 100%),
  caption: [Estimated flight times from key Iranian launch sites to Tel Aviv by missile system. Values in minutes; distances shown in labels.],
)

== Flight Time Breakdown by Missile System

#table(
  columns: (2fr, 1fr, 1fr, 1fr, 1fr, 1.2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#F59E0B").lighten(85%) } else { none },
  align: center,
  [*Missile*], [*Peak Mach*], [*From Kermanshah*], [*From Tabriz*], [*From Isfahan*], [*From Semnan*],
  [Emad], [Mach 10], [6.5 min], [6.9 min], [8.8 min], [9.8 min],
  [Ghadr], [Mach 10], [6.5 min], [6.9 min], [8.8 min], [9.8 min],
  [Sejjil], [Mach 14], [4.9 min], [5.2 min], [6.6 min], [7.3 min],
  [Kheibar Shekan], [Mach 10], [5.9 min], [6.3 min], [8.0 min], [8.9 min],
  [Fattah-1], [Mach 13], [5.1 min], [5.4 min], [6.9 min], [7.7 min],
  [Fattah-2 (HGV)], [Mach 15], [4.3 min], [4.6 min], [5.9 min], [6.5 min],
  [Khorramshahr-4], [Mach 8], [8.1 min], [8.6 min], [11.0 min], [12.2 min],
)

#v(0.3cm)

*Key distances from Iranian launch sites to Tel Aviv:*
- Kermanshah (western): 1,171 km — nearest major launch point
- Tabriz (northwestern): 1,242 km
- Isfahan (central): 1,588 km
- Shiraz (southern): 1,721 km
- Semnan (eastern): 1,762 km — farthest recorded launch point

== Implications for Defenders

The engagement window narrows dramatically with advanced missile systems:

- *Legacy systems (Emad/Ghadr from Kermanshah):* ~6.5 minutes. Sufficient for Arrow-2/Arrow-3 exoatmospheric interception and one endoatmospheric backup shot.
- *Fattah-2 HGV from Kermanshah:* ~4.3 minutes. Compresses the engagement window by a third. The HGV's lateral maneuvering further complicates terminal interception — Arrow-3 exoatmospheric engagement may be the only viable window.
- *Khorramshahr-4 (TP4 Wave 19):* Slower trajectory (~Mach 8) but carries 1-ton warheads. First confirmed combat use in TP4 — prioritizes payload over speed.
- *Solid-fuel advantage:* Sejjil, Kheibar Shekan, and Fattah all offer faster launch preparation. Solid-fuel missiles can be fired within minutes of TEL deployment; liquid-fuel Emad/Ghadr require 30+ minutes of fueling.

== Confirmed Advanced Missile Combat Use

#table(
  columns: (2fr, 1fr, 1fr, 2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#DC2626").lighten(85%) } else { none },
  align: center,
  [*System*], [*TP3 Waves*], [*TP4 Waves*], [*Notes*],
  [Fattah-1], [1 (Wave 11)], [0 confirmed], [First combat use in TP3; MaRV with thrust vector control],
  [Fattah-2 (HGV)], [0], [0 confirmed], [First combat use reported early TP4 per sources; wave attribution unclear],
  [Kheibar Shekan], [2 (W20, W21)], [1 (Wave 10)], [Multi-warhead variant debuted in TP3 W20],
  [Sejjil], [1 (Wave 12)], [0 confirmed], [First-ever combat deployment; ~8 missiles in TP3 W12],
  [Khorramshahr-4], [0], [1 (Wave 19)], [*New in TP4* — 1-ton warhead, first confirmed combat use],
)

#v(0.3cm)

*Trend:* TP3 saw the *introduction* of Iran's most advanced systems late in the campaign (waves 11, 12, 20–21), suggesting they were held in reserve and deployed as escalation tools. In TP4, Kheibar Shekan appeared at wave 10, Khorramshahr-4 at wave 19, and Fattah-2 was reportedly used early — indicating Iran is deploying advanced systems earlier rather than holding them back.

The Khorramshahr-4 is a new development: targeting USS Abraham Lincoln (CVN-72) at wave 19 suggests Iran is using heavy ballistic missiles against naval targets — a significant doctrinal extension.

#pagebreak()

// ============================================================
// 4. WEAPON MIX EVOLUTION
// ============================================================

= Weapon Mix Evolution

== From Ballistic-Dominant to Drone-Integrated

The most striking doctrinal shift between TP3 and TP4 is the integration of drones into nearly every wave.

#figure(
  image("report_01_weapon_mix.png", width: 100%),
  caption: [Weapon categories per wave. TP3 relied almost exclusively on ballistic missiles; TP4 integrates drones into 84% of waves and cruise missiles into 16%.],
)

#figure(
  image("report_03_drone_ratio.png", width: 100%),
  caption: [Cumulative drone integration rate by wave. TP3 stabilizes at 32%; TP4 reaches 84% by wave 16.],
)

== Weapon System Heatmap

#figure(
  image("report_05_weapon_heatmap.png", width: 100%),
  caption: [Individual weapon system usage by wave. Dark = confirmed used; light = unknown/null. TP3 is Emad/Ghadr-dominated; TP4 is Shahed-136-dominated.],
)

*TP3 weapon profile:*
- Emad: 20 of 22 waves (91%) — the backbone of TP3
- Ghadr: 21 of 22 waves (95%) — paired with Emad in virtually every wave
- Shahed-136: 7 of 22 waves (32%) — supplementary role
- Advanced systems introduced late: Fattah W11, Sejjil W12, Kheibar Shekan W20–21

*TP4 weapon profile:*
- Shahed-136: 15 of 19 waves (79%) — now the primary delivery system
- Emad: 2 of 19 waves (11%) — dramatically reduced
- Ghadr: 3 of 19 waves (16%) — dramatically reduced
- Cruise missiles: 3 of 19 waves (16%) — *new category entirely*, absent from TP3
- Kheibar Shekan: 1 of 19 waves (5%)
- Khorramshahr-4: 1 of 19 waves (Wave 19) — first combat use

== The Drone Pivot: Why?

The shift from ballistic-dominant (TP3) to drone-dominant (TP4) likely reflects several factors:

+ *Cost-exchange ratio:* A Shahed-136 costs \$20,000–50,000. An Arrow-3 interceptor costs \$2–3 million. Forcing defenders to expend premium interceptors on cheap drones is a deliberate attrition strategy. In TP3, Israel reportedly consumed a significant portion of its Arrow inventory.

+ *Production capacity:* Iran can manufacture Shahed-136 drones at industrial scale. Ballistic missile production is slower and more resource-intensive. After TP3 consumed 550+ ballistic missiles, Iran may have faced inventory constraints driving greater drone reliance in TP4.

+ *Multi-theater demands:* TP4 targets 12 countries simultaneously. Drones are more suitable for distributed, lower-priority targets (Gulf shipping lanes, Omani ports) while reserving ballistic missiles for hardened Israeli and US base targets.

+ *Lessons from Ukraine:* Russia's sustained Shahed campaigns against Ukraine demonstrated that drone saturation degrades air defense networks over time, even when individual drones are intercepted.

#pagebreak()

// ============================================================
// 5. DRONE INVENTORY
// ============================================================

= Iranian Drone Systems Identified

Based on OSINT research, the following drone/UAV systems have been confirmed or assessed as used in TP3 and/or TP4:

== One-Way Attack UAVs (Loitering Munitions)

#table(
  columns: (1.5fr, 1fr, 1fr, 1fr, 1fr, 1fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#10B981").lighten(85%) } else { none },
  align: center,
  [*System*], [*Speed*], [*Range*], [*Warhead*], [*Weight*], [*Unit Cost*],
  [Shahed-136], [185 km/h], [970–2,500 km], [50 kg], [200 kg], [\$20–50K],
  [Shahed-131], [185 km/h], [900 km], [15 kg], [135 kg], [\$10–20K],
  [Shahed-238], [500–700 km/h], [1,200 km], [50 kg], [—], [—],
  [Shahed-107], [—], [1,500 km], [15 kg], [—], [—],
)

- *Shahed-136 (Geran-2):* The workhorse of both operations. Used in 32% of TP3 waves and 79% of TP4 waves. Piston-engine, delta-wing, GPS-guided. Slow but cheap — designed to saturate. Wave 16 of TP4 alone launched 230 attack drones.
- *Shahed-131 (Geran-1):* Smaller companion launched in mixed swarms with the 136. Carries Iridium satellite link for mid-flight re-targeting — a capability the 136 lacks.
- *Shahed-238 (Geran-3):* Jet-powered, 2.7× faster than the 136. Three seeker variants (GPS, infrared, radio-frequency). Ceiling of 9,144m — comparable to combat aircraft.
- *Shahed-107:* Anti-jamming navigation, X-shaped tail, carbon-fiber airframe. Intercepted by UAE F-16s and Mirage 2000-9s during TP4.

== MALE/Strike UAVs

- *Shahed-129:* MALE reconnaissance/strike platform (comparable to MQ-1 Predator). 24-hour endurance, 16m wingspan.
- *Mohajer-6:* Tactical armed UCAV. Present aboard IRIS Shahid Bagheri drone carrier (sunk Feb 28, 2026). Likely also operated from land bases.

== Systems Lost with IRIS Shahid Bagheri

Iran's drone carrier was struck and sunk by US forces on TP4's first day (Wave 1, Feb 28, 2026). It reportedly carried:
- Ababil-3N carrier drones
- Mohajer-6 armed UCAVs
- JAS-313 stealth drones (Qaher-313 derivative)
- Homa VTOL drones

These were destroyed before deployment, disrupting Iran's planned naval drone component.

#pagebreak()

// ============================================================
// 6. GEOGRAPHIC EXPANSION
// ============================================================

= Geographic Expansion: From Israel to Multi-Theater

== The Single Most Important Doctrinal Shift

TP3 targeted exclusively Israel across all 22 waves. TP4 expanded to 12 countries — the most significant escalation in Iranian strike doctrine since the program's inception.

#figure(
  image("report_04_target_geography.png", width: 100%),
  caption: [TP4 target countries ranked by wave count. Israel (14 waves), Iraq (13), Bahrain (11), UAE (8), Qatar (8), Jordan (6), Oman (4), Kuwait (3), Saudi Arabia (2), Turkey (1), Cyprus (1), Diego Garcia/IO (1).],
)

#figure(
  image("report_10_map.png", width: 100%),
  caption: [Schematic attack geography. Purple triangles = Iranian launch sites. Blue circles = TP3 targets (Israel). Red squares = TP4 regional targets.],
)

== TP4 Target Categories

#table(
  columns: (1.5fr, 2fr, 2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#DC2626").lighten(85%) } else { none },
  [*Category*], [*Targets*], [*Significance*],
  [Israeli military], [Nevatim AB, Tel Nof AB, Kirya IDF HQ, Ramat David AB], [Continuation of TP3 targeting],
  [Israeli civilian], [Tel Aviv metro, Haifa, Jerusalem, Ben Gurion Airport], [Continuation of TP3 targeting],
  [US air bases], [Al Udeid (QA), Al Dhafra (AE), Ali Al Salem (KW), Al Asad (IQ), Harir (IQ), Prince Sultan (SA)], [*New in TP4* — direct strikes on US forward bases],
  [US naval], [NSA Bahrain / 5th Fleet HQ, USS Abraham Lincoln (CVN-72)], [*New in TP4* — targeting US naval infrastructure and carriers],
  [Gulf infrastructure], [Jebel Ali port (AE), Duqm port (OM), commercial tankers, Amazon data center (BH)], [*New in TP4* — economic/shipping disruption],
  [Other coalition], [Akrotiri (CY), Diego Garcia (IO), French base Abu Dhabi], [*New in TP4* — extreme range targeting],
)

== Dual-Front Targeting Pattern

#figure(
  image("report_06_dual_front.png", width: 100%),
  caption: [TP4 wave-by-wave targeting: Israel (blue) vs US/coalition bases (red). US bases are targeted in 16 of 19 waves vs Israel in 14 of 19 waves.],
)

In TP4, Israel was targeted in 14 of 19 waves (74%). US/coalition bases were targeted in 16 of 19 waves (84%). Notably, US bases are targeted *more frequently* than Israel in TP4 — a complete reversal of TP3's Israel-only focus. This targeting inversion suggests Iran views US military infrastructure in the Gulf as the primary adversary to be degraded, while maintaining Israel as a secondary target set.

== Escalation Staircase

#figure(
  image("report_09_escalation.png", width: 100%),
  caption: [Cumulative unique countries targeted per wave. TP3 = flat at 1 (Israel only). TP4 expanded to 12 countries across the first 6 days of the operation.],
)

*TP3 escalation pattern:* Weapon-driven. New missile types introduced at waves 11, 12, and 20. No new countries — always Israel.

*TP4 escalation pattern:* Geography-driven. The 12 countries in TP4's target set were established rapidly within the first few waves. New target types added progressively: naval vessels (Wave 1), civil infrastructure like Jebel Ali port (Wave 1), major US carriers (Wave 19). The 12-country target list represents a qualitative leap in the scope of Iran's declared war.

#pagebreak()

// ============================================================
// 7. TREND SYNTHESIS
// ============================================================

= Trend Synthesis: Six Shifts in Iranian Doctrine

#v(0.3cm)

== Trend 1: Saturation Over Precision

*TP3:* 550+ ballistic missiles, 1,000+ drones. High per-unit cost, moderate accuracy. \
*TP4:* Drone-led salvos with ballistic missile accompaniment. Low per-unit cost, volume-oriented. Wave 16 alone launched 230 attack drones — comparable to TP3's entire drone inventory across 7 waves.

*Evidence:* Drone integration jumped from 32% of waves (TP3) to 84% (TP4). The shift in composition reduces Iran's per-wave expenditure while maintaining pressure on air defense interceptor stocks.

== Trend 2: Tempo Acceleration

*TP3:* 10.5-hour average inter-wave gap. \
*TP4:* 5.4-hour average inter-wave gap — nearly 2× faster.

*Evidence:* TP4's maximum gap (14.0h) is shorter than TP3's average gap (10.5h). This compression is consistent with pre-positioned drone assets and solid-fuel ballistic missiles eliminating liquid-fuel setup delays. 19 waves in 6 days (TP4) vs 22 waves in 12 days (TP3) confirms the acceleration.

== Trend 3: Geographic Expansion

*TP3:* 1 country (Israel). \
*TP4:* 12 countries across 4 sub-regions.

*Evidence:* US bases targeted in 84% of waves — more than Israel (74%). Gulf shipping, Omani ports, Diego Garcia, and Akrotiri (Cyprus) all struck. The targeting of USS Abraham Lincoln at Wave 19 extends Iran's ballistic missile threat to US carrier groups for the first time.

== Trend 4: Shift from Liquid-Fuel to Drone-Led

*TP3:* Emad (91% of waves) and Ghadr (95%) dominated — both liquid-fueled MRBMs. \
*TP4:* Shahed-136 (79% of waves) dominates. Emad dropped to 11%, Ghadr to 16%.

*Evidence:* This shift may reflect inventory depletion after TP3's heavy ballistic missile expenditure, a deliberate cost-exchange strategy, or both. Cruise missiles (3 waves, 16%) appeared for the first time in any Iranian operation. The introduction of Khorramshahr-4 (Wave 19) adds a new heavy payload variant to the mix.

== Trend 5: Earlier Advanced Weapon Deployment

*TP3:* Advanced systems (Fattah-1 at W11, Sejjil at W12, Kheibar Shekan at W20–21) appeared in the campaign's second half. \
*TP4:* Kheibar Shekan appeared at wave 10. Fattah-2 HGV reportedly used by day 2. Khorramshahr-4 introduced at wave 19.

*Evidence:* Iran is no longer holding advanced systems in reserve as escalation leverage. They are being integrated from wave 10 onward, suggesting confidence in their survivability against preemptive strikes, or concern about losing them in a prolonged campaign.

== Trend 6: Multi-Domain Integration

*TP3:* Ballistic missiles + drones (supplementary). No cruise missiles. No naval dimension. \
*TP4:* Ballistic missiles + drones (primary) + cruise missiles (new) + anti-shipping operations + drone carrier deployment + naval vessel targeting.

*Evidence:* TP4 represents Iran's first attempt at a truly joint operation: land-based TEL launches, naval drone carrier operations (IRIS Shahid Bagheri, sunk Day 1), cruise missile employment, and coordination of Gulf-wide OWA drone swarms. The loss of the Shahid Bagheri on day 1 disrupted the naval component, but the doctrinal intent was multi-domain. Targeting of USS Abraham Lincoln at Wave 19 with Khorramshahr-4 ballistic missiles confirms Iran's ambition to engage US naval power at range.

#pagebreak()

// ============================================================
// 8. OPERATION TIMELINES
// ============================================================

= Operation Timelines

== True Promise 3 (TP3) — June 13–24, 2025

#table(
  columns: (0.8fr, 1.2fr, 2fr, 2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#2563EB").lighten(85%) } else if calc.rem(y, 2) == 0 { rgb("#f8f8f8") } else { none },
  align: (left, left, left, left),
  [*Wave*], [*Date (UTC)*], [*Weapons*], [*Key Events*],
  [1], [Jun 13], [Emad, Ghadr, Shahed-136], [Operation opens; ~100 BMs + drones; Bat Yam 9 killed],
  [2–3], [Jun 13–14], [Emad, Ghadr, drones], [Multi-wave day 1; Haifa power plant struck],
  [4–7], [Jun 14–15], [Emad, Ghadr], [Sustained BM campaign; Petah Tikva building 4 killed],
  [8], [Jun 16], [Emad, Ghadr], [Hundreds of missiles; Soroka Hospital Beersheba struck],
  [9–10], [Jun 17–18], [Emad, Ghadr], [Bazan Haifa refinery struck (3 killed); Weizmann Institute hit],
  [11], [Jun 19], [Fattah-1, Emad, Ghadr], [*First Fattah-1 combat use*; Glilot intel base hit],
  [12], [Jun 19–20], [Sejjil (~8), Emad, Ghadr], [*First Sejjil combat deployment*; Tel Nof AB struck],
  [13–17], [Jun 20–22], [Emad, Ghadr, drones], [Continued barrage; Kirya IDF HQ struck],
  [18], [Jun 22], [Shahed-136, precision BMs], [New drone swarm tactics; Eshkol Power Station hit],
  [19], [Jun 22–23], [Emad, Ghadr, drones], [Combined large operation],
  [20], [Jun 23], [Kheibar Shekan (multi-warhead), Emad], [*First multi-warhead Kheibar Shekan* (40 missiles)],
  [21], [Jun 23–24], [Kheibar Shekan, Qadr-H], [New-gen multi-warhead systems; Rishon LeZion 2 killed],
  [22], [Jun 24], [14 missiles], [Final wave before ceasefire; Beersheba 4 killed],
)

== True Promise 4 (TP4) — February 28 – March 5+, 2026

#table(
  columns: (0.8fr, 1.2fr, 2fr, 2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#DC2626").lighten(85%) } else if calc.rem(y, 2) == 0 { rgb("#f8f8f8") } else { none },
  align: (left, left, left, left),
  [*Wave*], [*Date (UTC)*], [*Weapons*], [*Key Events*],
  [1], [Feb 28 18:30], [Emad, Ghadr, Shahed-136], [TP4 opens; IRIS Shahid Bagheri sunk by US; Nevatim + Bahrain + Jebel Ali + Gulf tankers targeted],
  [2], [Feb 28 21:00], [BMs, drones], [Tel Aviv + US bases in Iraq],
  [3], [Feb 28 23:45], [Advanced BMs, drones, cruise missiles], [Haifa naval base, Ramat David AB, Abdullah Al-Mubarak (KW), Harir (IQ), Prince Sultan (SA); Etihad Towers Abu Dhabi debris],
  [4], [Mar 1 01:00], [BMs, drones], [Multi-target wave],
  [5], [Mar 1 04:00], [BMs, drones, cruise missiles], [Mixed arms wave],
  [6], [Mar 1 08:00], [BMs, drones], [Daytime salvo],
  [7], [Mar 1 14:00], [BMs, drones, cruise missiles], [Cruise missile wave — third use],
  [8], [Mar 1 18:00], [BMs, drones], [Evening wave],
  [9], [Mar 1 22:00], [BMs, drones], [Night wave],
  [10], [Mar 2 04:00], [Kheibar Shekan], [*Kheibar Shekan* maneuvering BMs — first TP4 use],
  [11], [Mar 2 10:00], [BMs, drones], [Morning wave Day 3],
  [12], [Mar 2 14:30], [26 drones, 5 BMs], [Drone-heavy wave],
  [13], [Mar 2 19:00], [Drones], [Pure drone wave],
  [14], [Mar 3 02:00], [20 drones, 3 BMs], [Small mixed wave],
  [15], [Mar 3 16:00], [BMs, drones], [Day 4 afternoon],
  [16], [Mar 4 06:00], [230 drones, BMs], [*Largest drone wave* — 230 OWA drones],
  [17], [Mar 4 09:00], [40+ BMs], [Major ballistic salvo],
  [18], [Mar 4 (est.)], [Ghadr-class BMs], [Codename: Ya Imam Hassan Mojtaba — timing unconfirmed],
  [19], [Mar 5 06:00], [Khorramshahr-4 BMs (1t warheads), drones], [*First Khorramshahr-4 combat use*; targets USS Abraham Lincoln (CVN-72); Israeli Defense Ministry, Ben Gurion Airport, Jerusalem],
)

#pagebreak()

// ============================================================
// 9. DATA SOURCES AND METHODOLOGY
// ============================================================

= Data Sources and Methodology

== Primary Sources

This analysis is based on wave-level JSON datasets maintained in the `Iran-Israel-War-2026-Data` repository:

- *TP3:* 22 waves, partial munitions counts. Cross-referenced against Wikipedia "List of attacks during the Twelve-Day War", FPRI analysis, and FDD tracking.
- *TP4:* 19 waves (ongoing as of 05 March 2026), limited munitions counts. Cross-referenced against Critical Threats daily updates, defense media (Defense Update, DefenseScoop, Aviation Week).

== Weapon Specifications

Missile and drone technical data sourced from CSIS Missile Threat Project, GlobalSecurity.org, IISS assessments, manufacturer disclosures, and Wikipedia military articles. Flight time estimates use haversine distances and empirical average ballistic trajectory speeds (3.0–4.5 km/s depending on system type).

== Key Source URLs

- FPRI: "Shallow Ramparts: Air and Missile Defenses in the June 2025 Israel-Iran War"
- Carnegie: "What We Know About Drone Use in the Iran War"
- Critical Threats: "Iran Update Morning Special Report: March 3–5, 2026"
- Defense Update: "Operation Epic Fury / Roaring Lion"
- NBC News: "Iran Leans on Shahed Drones to Penetrate U.S. Defenses"
- FDD: Iranian drone and missile attack tracking (June 2025)
- Army Recognition: UAE combat interception of Shahed-136 and Shahed-107

== External Data Sources for Cross-Reference

For researchers seeking to cross-check or expand upon this data:

- *GDELT (Global Database of Events, Language, and Tone):* BigQuery table `gdelt-bq.gdeltv2.events_partitioned` — filter on `Actor1CountryCode='IRN'`, `Actor2CountryCode='ISR'`, `EventRootCode='19'` (conventional military force).
- *ACLED:* Geocoded conflict event data. Free API access at `acleddata.com` — filter by Iran/Israel, event dates.
- *GeoConfirmed:* Volunteer OSINT geolocating visual conflict content.
- *Oryx:* Equipment loss tracking with photographic evidence.

== Data Quality Observations

- TP4 is *ongoing* at time of publication. Data is incomplete — wave 18 lacks a confirmed timestamp.
- Munitions counts are sparse for both operations — most waves lack confirmed totals.
- Solar phase data for TP3 shows 14 of 22 waves as "Daylight" (phase 5), which may reflect data entry conventions rather than all-daylight launches; independent verification of launch times is recommended.
- The `houthi_involved` proxy field is null for all 41 waves in the current dataset — a known data gap. Houthi coordination with Iran is documented in aggregate reporting for both operations but has not been attributed to specific waves.
- Wave 18 (TP4) has no timing data — conflict day 5 is confirmed but exact launch time is unverified.
- Weapon type attributions marked `null` (vs `false`) indicate unknown rather than confirmed absence.

#v(1cm)

#align(center)[
  #rect(fill: rgb("#f5f5f5"), inset: 1em, radius: 4pt)[
    #text(size: 9pt, fill: rgb("#666"))[
      This report was generated by Anthropic Claude Sonnet 4.6 on 05/03/26. \
      It is based entirely on open-source information and contains no classified material. \
      All data, charts, and analysis should be independently verified before use in decision-making. \
      TP3: 22 waves (Jun 13–24, 2025) | TP4: 19 waves (Feb 28–Mar 5+, 2026) | Total: 41 waves
    ]
  ]
]
