// Iranian Attack Pattern Evolution: True Promise 3 vs True Promise 4
// Comparative OSINT Analysis

#set text(font: "IBM Plex Sans", size: 10pt)
#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2cm, right: 2cm),
  header: context {
    if counter(page).get().first() > 1 [
      #set text(size: 8pt, fill: rgb("#666"))
      Iranian Attack Pattern Evolution: TP3 vs TP4 — Comparative OSINT Analysis
      #h(1fr)
      #counter(page).display()
    ]
  },
  footer: [
    #set text(size: 7pt, fill: rgb("#999"))
    #align(center)[
      AI-GENERATED (Anthropic Claude Opus 4.6) · Generated 05/03/26 03:24 UTC · All facts require independent verification
    ]
  ]
)
#set par(justify: true, leading: 0.7em)
#set heading(numbering: "1.1")

// ============================================================
// TITLE PAGE
// ============================================================

#v(3cm)

#align(center)[
  #text(size: 28pt, weight: "bold", fill: rgb("#1a1a1a"))[
    Iranian Attack Pattern Evolution
  ]
  #v(0.5cm)
  #text(size: 16pt, fill: rgb("#444"))[
    Operation True Promise 3 (June 2025) vs \
    Operation True Promise 4 (February–March 2026)
  ]
  #v(1cm)
  #line(length: 60%, stroke: 1pt + rgb("#DC2626"))
  #v(0.8cm)
  #text(size: 12pt, fill: rgb("#666"))[
    Comparative OSINT Analysis
  ]
  #v(2cm)
  #text(size: 10pt, fill: rgb("#888"))[
    *Author:* Anthropic Claude Opus 4.6 (AI-generated analysis) \
    *Date of generation:* 05/03/26 at 03:24 UTC \
    *Data status:* TP4 ongoing as of publication \
    *Classification:* Open source — no classified material \
    \
    #rect(fill: rgb("#FEF2F2"), inset: 0.6em, radius: 3pt, stroke: 0.5pt + rgb("#DC2626"))[
      #text(size: 8pt, fill: rgb("#991B1B"), weight: "bold")[
        This report was entirely generated by AI. All facts, figures, and analysis \
        must be independently verified before citation or use in decision-making.
      ]
    ]
  ]
]

#pagebreak()

// ============================================================
// TABLE OF CONTENTS
// ============================================================

#outline(indent: 1.5em, depth: 2)

#pagebreak()

// ============================================================
// 1. EXECUTIVE SUMMARY
// ============================================================

= Executive Summary

Iran's missile and drone campaigns against Israel have undergone a fundamental transformation between Operation True Promise 3 (TP3, June 2025) and Operation True Promise 4 (TP4, February--March 2026). This report identifies and documents six major shifts in Iranian attack doctrine, supported by wave-level data from 40 combined attack waves.

#v(0.3cm)

#table(
  columns: (1fr, 1fr, 1fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#2563EB").lighten(85%) } else { none },
  align: center,
  [*Metric*], [*TP3 (Jun 2025)*], [*TP4 (Feb–Mar 2026)*],
  [Total waves], [22], [18 (ongoing)],
  [Duration], [12 days], [5+ days (ongoing)],
  [Countries hit], [1 (Israel)], [12],
  [Avg inter-wave gap], [10.5 hours], [5.4 hours],
  [Drone waves], [7 of 22 (32%)], [15 of 18 (83%)],
  [BM waves], [22 of 22 (100%)], [17 of 18 (94%)],
  [Cruise missile waves], [0 of 22 (0%)], [3 of 18 (17%)],
  [US bases targeted], [0 waves], [15 waves (83%)],
  [Night launches], [8 of 22 (36%)], [8 of 18 (44%)],
  [Recorded fatalities], [33 killed], [1+ (ongoing)],
  [Estimated munitions], [1,600--1,800+], [Data incomplete],
)

#v(0.3cm)

*Key finding:* TP4 represents a doctrinal shift from a focused, Israel-only ballistic missile campaign to a multi-theater, multi-domain operation integrating drones, ballistic missiles, and cruise missiles against both Israeli and US/coalition targets across 12 countries.

#pagebreak()

// ============================================================
// 2. ATTACK TEMPO
// ============================================================

= Attack Tempo and Operational Rhythm

== Inter-Wave Timing

The most immediate operational difference between TP3 and TP4 is attack tempo. TP4 waves arrive at nearly double the rate of TP3.

#figure(
  image("report_02_tempo.png", width: 100%),
  caption: [Inter-wave intervals in hours. TP4 (red) averages 5.4h between waves vs TP3 (blue) at 10.5h.],
)

*Evidence:*
- *TP3:* Average 10.5 hours between waves. Intervals ranged from 1.0h to 23.0h, suggesting a deliberate pacing strategy — likely driven by liquid-fuel missile reload times (Emad and Ghadr dominate TP3 with 20 and 21 waves respectively).
- *TP4:* Average 5.4 hours between waves. Maximum gap just 14.0h. This acceleration is consistent with greater reliance on solid-fuel missiles and pre-positioned drone launchers, which eliminate the 30+ minute liquid-fuel setup penalty.

The near-halving of inter-wave gaps suggests Iran learned from TP3 that spacing allowed Israeli/US defenses time to rearm and reposition interceptors. TP4's compressed tempo is designed to exhaust interceptor stocks more rapidly.

== Night vs Day Preference

#figure(
  image("report_08_night_day.png", width: 85%),
  caption: [Launch timing distribution. Both operations show a preference for night launches, but TP4 increases the night ratio.],
)

TP4 shows a modest increase in night operations (44% vs 36%), consistent with exploiting reduced visual detection and complicating defensive targeting. However, the shift is not dramatic — Iran launches around the clock in both operations.

#pagebreak()

// ============================================================
// 3. FLIGHT TIMES AND WARNING WINDOWS
// ============================================================

= Ballistic Missile Flight Times and Defender Warning Windows

This is among the most operationally significant dimensions of the data. The time between Iranian missile launch and Israeli impact determines the defender's engagement window — the seconds available for detection, tracking, classification, and interception.

#figure(
  image("report_07_flight_times.png", width: 100%),
  caption: [Estimated flight times from nearest (Kermanshah, western Iran) to farthest (Semnan, eastern Iran) launch sites to Tel Aviv. Ranges show min–max based on launch geography.],
)

== Flight Time Breakdown by Missile System

#table(
  columns: (2fr, 1fr, 1fr, 1fr, 1fr, 1.2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#F59E0B").lighten(85%) } else { none },
  align: center,
  [*Missile*], [*Peak Mach*], [*From Kermanshah*], [*From Tabriz*], [*From Isfahan*], [*From Semnan*],
  [Emad], [Mach 10], [6.5 min], [6.9 min], [8.8 min], [9.8 min],
  [Ghadr], [Mach 10], [6.5 min], [6.9 min], [8.8 min], [9.8 min],
  [Sejjil], [Mach 14], [5.6 min], [5.9 min], [7.6 min], [8.4 min],
  [Kheibar Shekan], [Mach 10], [5.1 min], [5.4 min], [7.0 min], [7.7 min],
  [Fattah-1], [Mach 13], [5.1 min], [5.4 min], [7.0 min], [7.7 min],
  [Fattah-2 (HGV)], [Mach 15], [4.3 min], [4.6 min], [5.9 min], [6.5 min],
)

#v(0.3cm)

*Key distances from Iranian launch sites to Tel Aviv:*
- Kermanshah (western): 1,171 km — nearest launch point
- Tabriz (northwestern): 1,242 km
- Isfahan (central): 1,588 km
- Shiraz (southern): 1,721 km
- Semnan (eastern): 1,762 km — farthest launch point

== Implications for Defenders

The engagement window narrows dramatically with advanced missile systems:

- *Legacy systems (Emad/Ghadr from Kermanshah):* ~6.5 minutes. Sufficient for Arrow-2/Arrow-3 exoatmospheric interception and one endoatmospheric backup shot.
- *Fattah-2 HGV from Kermanshah:* ~4.3 minutes. Compresses the engagement window by a third. The HGV's lateral maneuvering further complicates terminal interception — Arrow-3 exoatmospheric engagement may be the only viable window.
- *Solid-fuel advantage:* Sejjil, Kheibar Shekan, and Fattah all offer faster flight AND faster launch preparation. Solid-fuel missiles can be fired within minutes of TEL deployment; liquid-fuel Emad/Ghadr require 30+ minutes of fueling.

== Confirmed Advanced Missile Combat Use

#table(
  columns: (2fr, 1fr, 1fr, 2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#DC2626").lighten(85%) } else { none },
  align: center,
  [*System*], [*TP3 Waves*], [*TP4 Waves*], [*Notes*],
  [Fattah-1], [1 (Wave 11)], [0], [First combat use in TP3; MaRV with thrust vector control],
  [Fattah-2 (HGV)], [0], [0 confirmed], [First combat use reported 01/03/26 per sources; not yet attributed to specific wave],
  [Kheibar Shekan], [2 (W20, W21)], [1 (Wave 10)], [Multi-warhead variant debuted in TP3 W20],
  [Sejjil], [1 (Wave 12)], [0], [First-ever combat deployment; ~8 missiles in TP3 W12],
)

#v(0.3cm)

*Trend:* TP3 saw the *introduction* of Iran's most advanced systems late in the campaign (waves 11, 12, 20--21), suggesting they were held in reserve and deployed as escalation tools. In TP4, the Kheibar Shekan appeared by wave 10, and Fattah-2 reportedly saw first combat use — indicating Iran is deploying advanced systems earlier rather than holding them back.

The low confirmed counts are notable: despite possessing these systems, Iran continues to rely overwhelmingly on Emad, Ghadr, and Shahed-136 for the bulk of its salvos. Advanced missiles appear to be used selectively against high-value or hardened targets, not for saturation.

#pagebreak()

// ============================================================
// 4. WEAPON MIX EVOLUTION
// ============================================================

= Weapon Mix Evolution

== From Ballistic-Dominant to Drone-Integrated

The most striking doctrinal shift between TP3 and TP4 is the integration of drones into nearly every wave.

#figure(
  image("report_01_weapon_mix.png", width: 100%),
  caption: [Weapon categories per wave. TP3 relied almost exclusively on ballistic missiles; TP4 integrates drones into 83% of waves.],
)

#figure(
  image("report_03_drone_ratio.png", width: 100%),
  caption: [Cumulative drone integration rate. TP3 peaks at ~32%; TP4 reaches 83% by wave 15.],
)

== Weapon System Heatmap

#figure(
  image("report_05_weapon_heatmap.png", width: 100%),
  caption: [Individual weapon system usage by wave. Dark = confirmed used; light = unknown/null. TP3 is Emad/Ghadr-dominated; TP4 is Shahed-136-dominated.],
)

*TP3 weapon profile:*
- Emad: 20 of 22 waves (91%) — the backbone
- Ghadr: 21 of 22 waves (95%) — paired with Emad
- Shahed-136: 7 of 22 waves (32%) — supplementary role
- Advanced systems introduced late (Fattah W11, Sejjil W12, Kheibar Shekan W20--21)

*TP4 weapon profile:*
- Shahed-136: 15 of 18 waves (83%) — now the backbone
- Emad: 2 of 18 waves (11%) — dramatically reduced
- Ghadr: 3 of 18 waves (17%) — dramatically reduced
- Cruise missiles: 3 of 18 waves (17%) — *new category entirely*
- Kheibar Shekan: 1 of 18 waves (6%)

== The Drone Pivot: Why?

The shift from ballistic-dominant (TP3) to drone-dominant (TP4) likely reflects several factors:

+ *Cost-exchange ratio:* A Shahed-136 costs \$20,000--50,000. An Arrow-3 interceptor costs \$2--3 million. Forcing defenders to expend premium interceptors on cheap drones is a deliberate attrition strategy. In TP3, Israel reportedly consumed a significant portion of its Arrow inventory.

+ *Production capacity:* Iran can manufacture Shahed-136 drones at industrial scale. Ballistic missile production is slower and more resource-intensive. After TP3 consumed 550+ ballistic missiles, Iran may have faced inventory constraints.

+ *Multi-theater demands:* TP4 targets 12 countries simultaneously. Drones are more suitable for distributed, lower-priority targets (Gulf shipping lanes, Omani ports) while reserving ballistic missiles for hardened Israeli targets.

+ *Lessons from Ukraine:* Russia's sustained Shahed campaigns against Ukraine demonstrated that drone saturation degrades air defense networks over time, even when individual drones are intercepted.

#pagebreak()

// ============================================================
// 5. DRONE INVENTORY
// ============================================================

= Iranian Drone Systems Identified

Based on OSINT research, the following drone/UAV systems have been confirmed or assessed as used in TP3 and/or TP4:

== One-Way Attack UAVs (Loitering Munitions)

#table(
  columns: (1.5fr, 1fr, 1fr, 1fr, 1fr, 1fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#10B981").lighten(85%) } else { none },
  align: center,
  [*System*], [*Speed*], [*Range*], [*Warhead*], [*Weight*], [*Unit Cost*],
  [Shahed-136], [185 km/h], [970--2,500 km], [50 kg], [200 kg], [\$20--50K],
  [Shahed-131], [185 km/h], [900 km], [15 kg], [135 kg], [\$10--20K],
  [Shahed-238], [500--700 km/h], [1,200 km], [50 kg], [—], [—],
  [Shahed-107], [—], [1,500 km], [15 kg], [—], [—],
)

- *Shahed-136 (Geran-2):* The workhorse. Over 541 launched against UAE alone in TP4's first 48 hours. Piston-engine, delta-wing, GPS-guided. Slow but cheap — designed to saturate.
- *Shahed-131 (Geran-1):* Smaller companion launched in mixed swarms with the 136. Carries Iridium satellite link for mid-flight re-targeting — a capability the 136 lacks.
- *Shahed-238 (Geran-3):* Jet-powered, 2.7× faster than the 136. Three seeker variants (GPS, infrared, radio-frequency). Ceiling of 9,144m — comparable to combat aircraft. Used in TP4.
- *Shahed-107:* Intercepted by UAE F-16s and Mirage 2000-9s during TP4. X-shaped tail, carbon-fiber airframe, anti-jamming navigation.

== MALE/Strike UAVs

- *Shahed-129:* MALE reconnaissance/strike platform (comparable to MQ-1 Predator). 24-hour endurance, 16m wingspan. At least one confirmed loss on the ground in 2026.
- *Mohajer-6:* Tactical armed UCAV. Present aboard IRIS Shahid Bagheri drone carrier (sunk Feb 28, 2026). Likely also operated from land bases.

== Systems Lost with IRIS Shahid Bagheri

Iran's drone carrier was struck and sunk by US forces on TP4's first day. It carried:
- Ababil-3N carrier drones
- Mohajer-6 armed UCAVs
- JAS-313 stealth drones (Qaher-313 derivative)
- Homa VTOL drones

These were destroyed before deployment.

#pagebreak()

// ============================================================
// 6. GEOGRAPHIC EXPANSION
// ============================================================

= Geographic Expansion: From Israel to Multi-Theater

== The Single Most Important Doctrinal Shift

TP3 targeted exclusively Israel across all 22 waves. TP4 expanded to 12 countries — the most significant escalation in Iranian strike doctrine.

#figure(
  image("report_04_target_geography.png", width: 100%),
  caption: [Countries hit by wave count. TP3 = Israel only. TP4 = 12 countries across 4 sub-regions.],
)

#figure(
  image("report_10_map.png", width: 100%),
  caption: [Schematic attack geography. Red triangles = Iranian launch sites. Blue circles = TP3 targets (Israel). Red squares = TP4 regional targets.],
)

== TP4 Target Categories

#table(
  columns: (1.5fr, 2fr, 2fr),
  stroke: 0.5pt + rgb("#ddd"),
  fill: (x, y) => if y == 0 { rgb("#DC2626").lighten(85%) } else { none },
  [*Category*], [*Targets*], [*Significance*],
  [Israeli military], [Nevatim AB, Tel Nof AB, Kirya IDF HQ], [Continuation of TP3 targeting],
  [Israeli civilian], [Tel Aviv metro, Haifa, Beersheba], [Continuation of TP3 targeting],
  [US air bases], [Al Udeid (QA), Al Dhafra (AE), Ali Al Salem (KW), Al Asad (IQ), Incirlik (TR)], [*New in TP4* — direct strikes on US forward bases],
  [US naval], [NSA Bahrain (5th Fleet HQ), USN vessels in Gulf], [*New in TP4* — targeting US naval infrastructure],
  [Gulf infrastructure], [Jebel Ali port (AE), Duqm port (OM), commercial tankers], [*New in TP4* — economic/shipping disruption],
  [Other], [Diego Garcia (IO), Cyprus (Akrotiri)], [*New in TP4* — extreme range targeting],
)

== Dual-Front Targeting Pattern

#figure(
  image("report_06_dual_front.png", width: 100%),
  caption: [TP4 wave-by-wave targeting: Israel (blue) vs US bases (red). Both are targeted simultaneously in most waves.],
)

Israel was targeted in 13 of 18 TP4 waves (72%). US bases were targeted in 15 of 18 waves (83%). Notably, US bases are targeted *more frequently* than Israel in TP4 — a reversal of TP3's Israel-only focus.

== Escalation Staircase

#figure(
  image("report_09_escalation.png", width: 100%),
  caption: [Escalation events. TP3 escalated via new weapon systems. TP4 escalated via new countries — 6 country-escalation events in the first 11 waves.],
)

*TP3 escalation pattern:* Weapon-driven. New missile types introduced at waves 1, 11, 12, and 20. No new countries — always Israel.

*TP4 escalation pattern:* Geography-driven. New countries hit at waves 1, 3, 5, 7, 9, and 11. The first 11 waves each added at least one new country to the target set. This is a deliberate escalation strategy: gradually expanding the geographic scope to test coalition responses.

#pagebreak()

// ============================================================
// 7. TREND SYNTHESIS
// ============================================================

= Trend Synthesis: Six Shifts in Iranian Doctrine

#v(0.3cm)

== Trend 1: Saturation Over Precision

*TP3:* 550+ ballistic missiles, 1,000+ drones. High per-unit cost, moderate accuracy. \
*TP4:* Drone-led salvos (230+ in a single wave — Wave 16). Low per-unit cost, volume-oriented.

*Evidence:* Drone integration jumped from 32% of waves (TP3) to 83% (TP4). Wave 16 alone launched 230 attack drones — more than the total drone count of many TP3 waves combined.

== Trend 2: Tempo Acceleration

*TP3:* 10.5-hour average gap. \
*TP4:* 5.4-hour average gap — nearly 2× faster.

*Evidence:* TP4's maximum gap (14h) is shorter than TP3's average gap (10.5h). This compression is consistent with pre-positioned assets and solid-fuel dominance eliminating liquid-fuel setup delays.

== Trend 3: Geographic Expansion

*TP3:* 1 country (Israel). \
*TP4:* 12 countries.

*Evidence:* 6 new-country escalation events in TP4's first 11 waves. US bases targeted in 83% of waves — more than Israel (72%). Gulf shipping, Omani ports, and Diego Garcia all struck.

== Trend 4: Shift from Liquid-Fuel to Drone-Led

*TP3:* Emad (91% of waves) and Ghadr (95%) dominated — both liquid-fueled MRBMs. \
*TP4:* Shahed-136 (83% of waves) dominates. Emad dropped to 11%, Ghadr to 17%.

*Evidence:* This shift may reflect inventory depletion after TP3's heavy ballistic missile expenditure, a deliberate cost-exchange strategy, or both. Cruise missiles (3 waves) appeared for the first time.

== Trend 5: Earlier Advanced Weapon Deployment

*TP3:* Advanced systems (Fattah-1, Sejjil, Kheibar Shekan) appeared in waves 11--21 (the campaign's second half). \
*TP4:* Kheibar Shekan appeared at wave 10. Fattah-2 HGV reportedly used by day 2.

*Evidence:* Iran is no longer holding advanced systems in reserve as escalation leverage. They are being integrated earlier, suggesting confidence in their survivability or concern about losing them to preemptive strikes.

== Trend 6: Multi-Domain Integration

*TP3:* Ballistic missiles + drones (supplementary). No cruise missiles. \
*TP4:* Ballistic missiles + drones (primary) + cruise missiles (new). Anti-shipping operations. Drone carrier deployment (IRIS Shahid Bagheri, sunk day 1).

*Evidence:* TP4 represents Iran's first attempt at a truly joint operation: land-based TEL launches, naval drone carrier operations, cruise missile employment, and coordination with Gulf-wide OWA drone swarms. The loss of the Shahid Bagheri on day 1 disrupted the naval component, but the doctrinal intent was multi-domain.

#pagebreak()

// ============================================================
// 8. DATA SOURCES AND METHODOLOGY
// ============================================================

= Data Sources and Methodology

== Primary Sources

This analysis is based on wave-level JSON datasets maintained in the `Iran-Israel-War-2026-Data` repository:

- *TP3:* 22 waves, partial munitions counts. Cross-referenced against Wikipedia "List of attacks during the Twelve-Day War", FPRI analysis, and FDD tracking.
- *TP4:* 18 waves (ongoing), limited munitions counts. Cross-referenced against Critical Threats daily updates, defense media (Defense Update, DefenseScoop, Aviation Week).

== Weapon Specifications

Missile and drone technical data sourced from CSIS Missile Threat Project, GlobalSecurity.org, IISS assessments, manufacturer disclosures, and Wikipedia military articles. Flight time estimates use haversine distances and empirical average ballistic trajectory speeds (3.0--4.5 km/s depending on system type).

== Key Source URLs

- FPRI: "Shallow Ramparts: Air and Missile Defenses in the June 2025 Israel-Iran War"
- Carnegie: "What We Know About Drone Use in the Iran War"
- Critical Threats: "Iran Update Morning Special Report: March 3, 2026"
- Defense Update: "Operation Epic Fury / Roaring Lion"
- NBC News: "Iran Leans on Shahed Drones to Penetrate U.S. Defenses"
- FDD: Iranian drone and missile attack tracking (June 2025)
- Army Recognition: UAE combat interception of Shahed-136 and Shahed-107

== External Data Sources for Cross-Reference

For researchers seeking to cross-check or expand upon this data:

- *GDELT (Global Database of Events, Language, and Tone):* BigQuery table `gdelt-bq.gdeltv2.events_partitioned` — filter on `Actor1CountryCode='IRN'`, `Actor2CountryCode='ISR'`, `EventRootCode='19'` (conventional military force). DOC API at `api.gdeltproject.org/api/v2/doc/doc` for media coverage volume.
- *ACLED:* Geocoded conflict event data. Free API access at `acleddata.com` — filter by Iran/Israel, event dates.
- *GeoConfirmed:* Volunteer OSINT geolocating visual conflict content.
- *Oryx:* Equipment loss tracking with photographic evidence.

== Limitations

- TP4 is *ongoing* at time of publication. Data is incomplete.
- Munitions counts are sparse for both operations — most waves lack confirmed totals.
- Weapon system attribution per wave relies on IRGC announcements and OSINT analysis; independent confirmation is limited.
- Flight time calculations are estimates based on average trajectory speeds, not exact ballistic simulations.
- The Shahed-131 is inferred as co-launched with Shahed-136 based on known mixed-swarm doctrine; per-wave confirmation is limited.

#v(1cm)

#align(center)[
  #rect(fill: rgb("#f5f5f5"), inset: 1em, radius: 4pt)[
    #text(size: 9pt, fill: rgb("#666"))[
      This report was generated by Anthropic Claude Opus 4.6 on 05/03/26. \
      It is based entirely on open-source information and contains no classified material. \
      All data, charts, and analysis should be independently verified before use in decision-making.
    ]
  ]
]
