#!/usr/bin/env python3
"""Generate daily SITREP HTML pages from wave data for GitHub Pages site."""

import json
import os
from datetime import datetime, timezone
from collections import defaultdict

DOCS_DIR = os.path.join(os.path.dirname(__file__), "docs")
SITREP_DIR = os.path.join(DOCS_DIR, "sitreps")
TP3_PATH = os.path.join(DOCS_DIR, "data", "tp3-waves.json")
TP4_PATH = os.path.join(DOCS_DIR, "data", "tp4-waves.json")

NAV_HTML = """\
<nav class="site-nav" aria-label="Main navigation">
  <div class="nav-inner">
    <a href="../index.html" class="nav-brand">
      <span class="brand-icon" aria-hidden="true">&#x2604;</span>
      Iran-Israel War 2026 Data
    </a>
    <ul class="nav-links" role="list">
      <li><a href="../index.html">Overview</a></li>
      <li><a href="../map.html">Map</a></li>
      <li><a href="../timeline.html">Timeline</a></li>
      <li><a href="../data.html">Data</a></li>
      <li><a href="../sitreps.html">Sitreps</a></li>
      <li><a href="../about.html">About</a></li>
    </ul>
  </div>
</nav>"""

AI_BANNER = """\
<div class="ai-banner">
  <span class="ai-badge">AI-GENERATED</span>
  This situation report was automatically generated by AI from structured OSINT data.
  It has not been reviewed or verified by a human analyst. Treat all figures as approximate.
</div>"""


def load_waves():
    with open(TP3_PATH) as f:
        tp3 = json.load(f)
    with open(TP4_PATH) as f:
        tp4 = json.load(f)
    return tp3, tp4


def get_wave_date(wave):
    """Extract date string (YYYY-MM-DD) from wave timing."""
    for field in ["probable_launch_time", "announced_utc"]:
        ts = wave.get("timing", {}).get(field)
        if ts:
            return ts[:10]
    return None


def group_waves_by_date(waves, operation):
    by_date = defaultdict(list)
    for w in waves:
        d = get_wave_date(w)
        if d:
            w["_operation"] = operation
            by_date[d].append(w)
    return by_date


def weapon_summary(wave):
    w = wave.get("weapons", {})
    parts = []
    if w.get("ballistic_missiles_used"):
        parts.append("Ballistic Missiles")
    if w.get("cruise_missiles_used"):
        parts.append("Cruise Missiles")
    if w.get("drones_used"):
        parts.append("Drones/UAVs")
    return ", ".join(parts) or "Unknown"


def target_summary(wave):
    t = wave.get("targets", {})
    return t.get("targets", "") or ""


def interception_summary(wave):
    i = wave.get("interception", {})
    if not i:
        return "No data"
    rate = i.get("estimated_intercept_rate")
    if rate is not None:
        return f"{rate*100:.0f}%"
    if i.get("intercepted"):
        return "Yes (rate unknown)"
    return "No data"


def impact_summary(wave):
    imp = wave.get("impact", {})
    parts = []
    f = imp.get("fatalities")
    inj = imp.get("injuries")
    if f:
        parts.append(f"{f} killed")
    if inj:
        parts.append(f"{inj} injured")
    dmg = imp.get("damage")
    if dmg:
        parts.append(dmg)
    return "; ".join(parts) if parts else "No confirmed impacts reported"


def format_time(iso_str):
    if not iso_str:
        return "Unknown"
    try:
        return iso_str[:16].replace("T", " ") + " UTC"
    except Exception:
        return iso_str


def generate_sitrep_html(date_str, waves, operation_meta):
    """Generate a single sitrep HTML page for a given date."""
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    date_display = dt.strftime("%B %d, %Y")
    day_of_week = dt.strftime("%A")

    # Determine operation(s) active on this day
    ops = set(w["_operation"] for w in waves)
    ops_str = " / ".join(sorted(ops))

    total_munitions = 0
    total_fatalities = 0
    total_injuries = 0
    for w in waves:
        m = w.get("munitions", {}).get("estimated_munitions_count")
        if m:
            total_munitions += m
        f = w.get("impact", {}).get("fatalities")
        if f:
            total_fatalities += f
        inj = w.get("impact", {}).get("injuries")
        if inj:
            total_injuries += inj

    # Build wave detail rows
    wave_rows = ""
    for w in sorted(waves, key=lambda x: x.get("timing", {}).get("probable_launch_time", "") or ""):
        wn = w.get("wave_number", "?")
        op = w["_operation"]
        mc = w.get("munitions", {}).get("estimated_munitions_count")
        mc_str = str(mc) if mc else "N/A"
        wave_rows += f"""
      <div class="sitrep-wave-card {op.lower()}">
        <div class="wave-header">
          <span class="wave-op-badge {op.lower()}">{op}</span>
          <span class="wave-id">Wave {wn}</span>
          <span class="wave-time">{format_time(w.get('timing', {}).get('probable_launch_time'))}</span>
        </div>
        <div class="wave-details">
          <div class="detail-row"><span class="detail-label">Weapons:</span> {weapon_summary(w)}</div>
          <div class="detail-row"><span class="detail-label">Munitions:</span> {mc_str}</div>
          <div class="detail-row"><span class="detail-label">Targets:</span> {target_summary(w) or 'N/A'}</div>
          <div class="detail-row"><span class="detail-label">Interception:</span> {interception_summary(w)}</div>
          <div class="detail-row"><span class="detail-label">Impact:</span> {impact_summary(w)}</div>
        </div>
      </div>"""

    generation_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SITREP {date_str} — Iran-Israel War 2026 Data</title>
  <meta name="description" content="AI-generated daily situation report for {date_display} — Iranian missile/drone attack wave summary.">
  <link rel="stylesheet" href="../css/style.css">
  <link rel="stylesheet" href="../css/sitrep.css">
</head>
<body>

{NAV_HTML}

<main>

  {AI_BANNER}

  <div class="page-header">
    <div class="label">Daily Situation Report</div>
    <h1>SITREP — {date_display}</h1>
    <p>{day_of_week} &mdash; {ops_str} &mdash; {len(waves)} wave(s) recorded</p>
  </div>

  <!-- BLUF -->
  <section class="section">
    <div class="section-title"><span class="dot"></span> Bottom Line Up Front (BLUF)</div>
    <div class="card bluf-card">
      <p>
        On <strong>{date_display}</strong>, <strong>{len(waves)}</strong> attack wave(s) were recorded
        under <strong>{ops_str}</strong>.
        {"Estimated total munitions fired: <strong>" + str(total_munitions) + "</strong>." if total_munitions else "Munitions counts not fully available for this date."}
        {"Casualties: <strong>" + str(total_fatalities) + " killed</strong>, <strong>" + str(total_injuries) + " injured</strong>." if (total_fatalities or total_injuries) else "No confirmed casualties reported for this date."}
      </p>
    </div>
  </section>

  <!-- Summary stats -->
  <div class="stats-grid">
    <div class="stat-card" style="--accent-color: var(--iran-orange);">
      <div class="stat-label">Waves</div>
      <div class="stat-value">{len(waves)}</div>
      <div class="stat-sub">{ops_str}</div>
    </div>
    <div class="stat-card" style="--accent-color: var(--iran-red);">
      <div class="stat-label">Est. Munitions</div>
      <div class="stat-value">{total_munitions if total_munitions else 'N/A'}</div>
      <div class="stat-sub">Total fired this day</div>
    </div>
    <div class="stat-card" style="--accent-color: var(--iran-amber);">
      <div class="stat-label">Fatalities</div>
      <div class="stat-value">{total_fatalities if total_fatalities else '0'}</div>
      <div class="stat-sub">Confirmed killed</div>
    </div>
    <div class="stat-card" style="--accent-color: var(--israel-blue);">
      <div class="stat-label">Injuries</div>
      <div class="stat-value">{total_injuries if total_injuries else '0'}</div>
      <div class="stat-sub">Confirmed injured</div>
    </div>
  </div>

  <!-- Wave details -->
  <section class="section">
    <div class="section-title"><span class="dot"></span> Wave Details</div>
    <div class="sitrep-waves">
      {wave_rows}
    </div>
  </section>

  <!-- Footer note -->
  <section class="section">
    <div class="callout">
      <strong>AI-Generated Content:</strong> This situation report was automatically generated
      from structured OSINT data by an AI system (Claude). It has not been reviewed by a human
      analyst. All figures are approximate and sourced from open-source reporting only.
      Generated: {generation_time}.
    </div>
  </section>

  <div class="sitrep-nav">
    <a href="../sitreps.html" class="btn btn-outline">&larr; All Sitreps</a>
  </div>

</main>

<footer class="site-footer">
  <p>
    Iran-Israel War 2026 Data &mdash; AI-Generated OSINT Dataset &mdash;
    <a href="https://github.com/danielrosehill/Iran-Israel-War-2026-Data" target="_blank" rel="noopener">GitHub Repository</a>
  </p>
</footer>

</body>
</html>"""
    return html


def generate_index_html(all_dates):
    """Generate the sitrep index page."""
    generation_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rows = ""
    for date_str, info in sorted(all_dates.items(), reverse=True):
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        date_display = dt.strftime("%B %d, %Y")
        day_of_week = dt.strftime("%a")
        ops = ", ".join(sorted(info["ops"]))
        rows += f"""
      <a href="sitreps/{date_str}.html" class="sitrep-index-card">
        <div class="sitrep-date">
          <span class="sitrep-day">{dt.strftime('%d')}</span>
          <span class="sitrep-month">{dt.strftime('%b %Y')}</span>
          <span class="sitrep-dow">{day_of_week}</span>
        </div>
        <div class="sitrep-meta">
          <div class="sitrep-title">SITREP — {date_display}</div>
          <div class="sitrep-summary">{info['wave_count']} wave(s) &mdash; {ops} &mdash; Est. {info['munitions'] or 'N/A'} munitions</div>
        </div>
        <div class="sitrep-badge-col">
          {"".join(f'<span class="wave-op-badge {op.lower()}">{op}</span> ' for op in sorted(info["ops"]))}
        </div>
      </a>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Sitreps — Iran-Israel War 2026 Data</title>
  <meta name="description" content="AI-generated daily situation reports tracking Iranian missile and drone attack waves.">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/sitrep.css">
</head>
<body>

<nav class="site-nav" aria-label="Main navigation">
  <div class="nav-inner">
    <a href="index.html" class="nav-brand">
      <span class="brand-icon" aria-hidden="true">&#x2604;</span>
      Iran-Israel War 2026 Data
    </a>
    <ul class="nav-links" role="list">
      <li><a href="index.html">Overview</a></li>
      <li><a href="map.html">Map</a></li>
      <li><a href="timeline.html">Timeline</a></li>
      <li><a href="data.html">Data</a></li>
      <li><a href="sitreps.html">Sitreps</a></li>
      <li><a href="about.html">About</a></li>
    </ul>
  </div>
</nav>

<main>

  <div class="ai-banner">
    <span class="ai-badge">AI-GENERATED</span>
    All situation reports on this page are automatically generated by AI from structured OSINT data.
    They have not been reviewed or verified by a human analyst.
  </div>

  <div class="page-header">
    <div class="label">Situation Reports</div>
    <h1>Daily Sitreps</h1>
    <p>
      AI-generated daily situation reports summarizing Iranian attack wave activity.
      Each sitrep covers all waves recorded on a given conflict day.
    </p>
  </div>

  <div class="stats-grid">
    <div class="stat-card" style="--accent-color: var(--iran-orange);">
      <div class="stat-label">Total Sitreps</div>
      <div class="stat-value">{len(all_dates)}</div>
      <div class="stat-sub">Conflict days covered</div>
    </div>
    <div class="stat-card" style="--accent-color: var(--iran-red);">
      <div class="stat-label">Date Range</div>
      <div class="stat-value mono" style="font-size: 16px;">{min(all_dates.keys())} — {max(all_dates.keys())}</div>
      <div class="stat-sub">TP3 + TP4</div>
    </div>
  </div>

  <section class="section">
    <div class="section-title"><span class="dot"></span> All Sitreps</div>
    <div class="sitrep-index">
      {rows}
    </div>
  </section>

  <section class="section">
    <div class="callout">
      <strong>AI-Generated Content:</strong> These situation reports are automatically generated
      from structured OSINT data by an AI system (Claude). They have not been reviewed by human
      analysts. All figures are approximate and sourced from open-source reporting only.
      Last generated: {generation_time}.
    </div>
  </section>

</main>

<footer class="site-footer">
  <p>
    Iran-Israel War 2026 Data &mdash; AI-Generated OSINT Dataset &mdash;
    <a href="https://github.com/danielrosehill/Iran-Israel-War-2026-Data" target="_blank" rel="noopener">GitHub Repository</a>
  </p>
</footer>

</body>
</html>"""
    return html


def main():
    tp3, tp4 = load_waves()

    # Group waves by date
    tp3_by_date = group_waves_by_date(tp3.get("waves", []), "TP3")
    tp4_by_date = group_waves_by_date(tp4.get("waves", []), "TP4")

    # Merge
    all_by_date = defaultdict(list)
    for d, ws in tp3_by_date.items():
        all_by_date[d].extend(ws)
    for d, ws in tp4_by_date.items():
        all_by_date[d].extend(ws)

    os.makedirs(SITREP_DIR, exist_ok=True)

    # Track index metadata
    index_data = {}

    for date_str, waves in sorted(all_by_date.items()):
        html = generate_sitrep_html(date_str, waves, {"tp3": tp3, "tp4": tp4})
        out_path = os.path.join(SITREP_DIR, f"{date_str}.html")
        with open(out_path, "w") as f:
            f.write(html)

        total_m = sum(
            w.get("munitions", {}).get("estimated_munitions_count", 0) or 0
            for w in waves
        )
        index_data[date_str] = {
            "wave_count": len(waves),
            "ops": set(w["_operation"] for w in waves),
            "munitions": total_m if total_m else None,
        }
        print(f"  Generated sitrep: {date_str} ({len(waves)} waves)")

    # Generate index
    index_html = generate_index_html(index_data)
    index_path = os.path.join(DOCS_DIR, "sitreps.html")
    with open(index_path, "w") as f:
        f.write(index_html)
    print(f"  Generated sitrep index: {len(index_data)} days")

    print(f"\nDone! {len(index_data)} sitreps generated in {SITREP_DIR}/")


if __name__ == "__main__":
    main()
